global:
  security:
    allowInsecureImages: true

images:
  airflow:
    repository: ${HARBOR_URL}/${HARBOR_PROJECT}/airflow
    tag: "${AIRFLOW_TAG}"
    pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-creds

executor: ${AIRFLOW_EXECUTOR}

# Airflow version
airflowVersion: 3.0.2

# Disable bundled DB/Redis
postgresql:
  enabled: false
redis:
  enabled: false

# External PostgreSQL and Redis configuration
data:
  metadataConnection:
    user: ${AIRFLOW_DB_USER}
    pass: ${AIRFLOW_DB_PASSWORD}
    protocol: postgresql
    host: ${AIRFLOW_DB_HOST}
    port: ${AIRFLOW_DB_PORT}
    db: ${AIRFLOW_DB_NAME}
    sslmode: disable
  brokerUrl: redis://:${AIRFLOW_REDIS_PASSWORD}@${AIRFLOW_REDIS_HOST}:${AIRFLOW_REDIS_PORT}/0
  resultBackendConnection:
    user: ${AIRFLOW_DB_USER}
    pass: ${AIRFLOW_DB_PASSWORD}
    protocol: postgresql
    host: ${AIRFLOW_DB_HOST}
    port: ${AIRFLOW_DB_PORT}
    db: ${AIRFLOW_DB_NAME}
    sslmode: disable

# Static secret keys for production
fernetKey: "fernet-key-change-me-in-production-32-char-key"
webserverSecretKey: "webserver-secret-key-change-me-in-production"

# ✅ Disable migrations (handled manually/patch)
migrateDatabaseJob:
  enabled: false

checkMigrations:
  enabled: false

# Ingress via Traefik + TLS
ingress:
  web:
    enabled: false
  apiServer:
    enabled: true
    ingressClassName: traefik
    path: "/"
    pathType: "Prefix"
    hosts:
      - name: ${AIRFLOW_HOST}
        tls:
          enabled: true
          secretName: ${TLS_SECRET_NAME}
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"

# Persistence for logs
persistence:
  enabled: true
  size: 20Gi
  accessMode: ReadWriteOnce

# Component-specific configurations
scheduler:
  waitForMigrations:
    enabled: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"

# Webserver (FAB auth, default port 8080)
webserver:
  enabled: true
  replicas: 1
  waitForMigrations:
    enabled: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  service:
    type: ClusterIP
    ports:
      - name: airflow-ui
        port: 8080 # ✅ restored default port
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    email: admin@example.com
    firstName: admin
    lastName: user
    password: admin
  env:
    - name: AIRFLOW__WEBSERVER__RBAC
      value: "True"
    - name: AIRFLOW__WEBSERVER__AUTHENTICATE
      value: "True"
    - name: AIRFLOW__WEBSERVER__AUTH_BACKEND
      value: "airflow.providers.fab.auth_manager.auth.FabAuthManager"
    # ❌ removed old OAUTH_PROVIDERS block (incompatible with Airflow 3.x)

workers:
  waitForMigrations:
    enabled: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"

triggerer:
  waitForMigrations:
    enabled: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"

dagProcessor:
  waitForMigrations:
    enabled: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"

apiServer:
  waitForMigrations:
    enabled: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"
  env:
    - name: AIRFLOW__API__AUTH_BACKEND
      value: "airflow.api.auth.backend.default"
    - name: AIRFLOW__API__ENABLE_EXPERIMENTAL_API
      value: "True"
