global:
  security:
    allowInsecureImages: true

image:
  registry: ${HARBOR_URL}
  repository: ${HARBOR_PROJECT}/redis
  tag: "${REDIS_TAG}"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: harbor-creds

architecture: standalone

auth:
  enabled: true
  password: ${REDIS_PASSWORD}

master:
  persistence:
    enabled: true
    size: 5Gi
    accessModes: [ReadWriteOnce]

  podSecurityContext:
    enabled: true
    fsGroup: 1001
    seccompProfile:
      type: RuntimeDefault

  containerSecurityContext:
    enabled: true
    runAsUser: 1001
    runAsNonRoot: true
    allowPrivilegeEscalation: false
    capabilities:
      drop: ["ALL"]

service:
  type: ClusterIP
  port: ${REDIS_PORT}
