image:
  registry: ${HARBOR_URL}
  repository: ${HARBOR_PROJECT}/postgresql
  tag: "${POSTGRES_IMAGE_TAG}"
  pullPolicy: IfNotPresent

auth:
  postgresPassword: ${POSTGRES_PASSWORD}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  database: ${POSTGRES_DB}

architecture: standalone

primary:
  persistence:
    enabled: true
    size: 10Gi
    accessModes:
      - ReadWriteOnce

service:
  type: ClusterIP
  port: 5432
